### ISSUE TITLE
Example 2.2.3:  "binom.R" not found by snippet

### ISSUE THREAD

**Issue by homerhanumat** [rpruim/fastR2#10]
`snippet("binom")` runs several snippets containing the string `"binom"`,  eventually throwing an error at `binom-grid.R`, but never runs `binom.R`.

Current workaround is `snippet("^binom\\.R$")` .

**Comment by rpruim** [comment]
I've reworked how `snippet()` finds things.  It now uses partial string matching against an internal list of chunk names as is aware of sequences of snippets.  When there are multiple matches, they are listed to help the user refine the request.

``` r
library(fastR2)

# Multiple partial matches are displayed
snippet("bin", execute = FALSE, view = FALSE)
#> Multiple matches found for `bin': 
#>   binom, binom-bayes, binom-cis, binom-grid, binom-lci, binom-odds-ci, binom-wald-ci, binomial-ztest

# Exact match is used
snippet("binom", execute = FALSE, view = FALSE)
#> 
#> ## snippet: binom

# snippet() is aware of sequential numbering
snippet("binom-b", execute = FALSE, view = FALSE)
#> 
#> ## snippet: binom-bayes01
#> 
#> ## snippet: binom-bayes02

# To get one chunk from a sequence, use the full name
snippet("binom-bayes01", execute = FALSE, view = FALSE)
#> 
#> ## snippet: binom-bayes01
```

Created on 2018-08-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
