### ISSUE TITLE
Suggested package "Devore6" has been removed from CRAN

### ISSUE THREAD

**Issue by znmeb** [rpruim/fastR2#2]
I installed 'fastR' with the suggestions turned on and it issued a warning that it couldn't find 'Devore6'. It's been archived - http://cran.r-project.org/web/packages/Devore6/index.html

**Comment by rpruim** [comment]
The new package (Devore7) includes a data set that is similar to the one I used from Devore6.  I'll update the snippet to use Devore7 (and emit a comment about the switch from Devore6 to Devore7).
