### ISSUE TITLE
broken link to additional materials

### ISSUE THREAD

**Issue by homerhanumat** [rpruim/fastR2#5]
In the Preface to the Second Edition a link is given to additional materials:

[http://www.ams.org/bookpages/amstext-28](http://www.ams.org/bookpages/amstext-28)

It appears to be broken.

**Comment by rpruim** [comment]
I think we are still waiting for AMS to build the page.

**Comment by homerhanumat** [comment]
OK

**Comment by rpruim** [comment]
For now, I've built out a page at http://rpruim.github.io/fastR2/.  I hope to add some more things over the summer.  Still not sure what the timeline is for AMS, but I'm guessing that page will be up pretty soon.

**Comment by rpruim** [comment]
The page is up, so I'm closing this.
