### ISSUE TITLE
References to geyser in package MASS

### ISSUE THREAD

**Issue by homerhanumat** [rpruim/fastR2#8]
In Exercise 1.20, perhaps refer to `geyser` as `MASS::geyser` (as you do on page 14 when the data is first referenced).

`library(fastR2)` enables access to the help file on `geyser`, but `geyser` itself does not get on the search path.  (Because **fastR2** depends on **mosaic** which in turn imports **MASS**?)  This could stymie students.

**Comment by rpruim** [comment]
Too late to fix the printed book, but I can add a note on the errata sheet.
